quiz/urls.py
from django.contrib import admin
from django.urls import path, include 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quizapp.urls', namespace="quizapp")),
    path("user/",include("useraccount.urls",namespace="user")),
]

quizapp/urls.py
from django.urls import path
from quizapp.views import home,result, q_question, progress, completed

app_name = "quizapp"
urlpatterns = [
    path("",home,name="home"),
    path("quiz-question/<int:categoryid>/",q_question,name="q_question"),
    path("result/",result,name="result"),
    path("progress/",progress,name="progress"),
    path("completed/",completed,name="completed"),
]

useraccount/urls.py
from django.urls import path
from useraccount.views import CustomLoginView, CustomRegisterView
from django.contrib.auth.views import LogoutView

app_name="user"

urlpatterns = [
    path("login/",CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", CustomRegisterView.as_view(), name="register"),
]

quizapp/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class TimeStampModal(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    
    class Meta:
        abstract = True
     


class Category(TimeStampModal):
    category = models.CharField(max_length=200)
    
    def __str__(self):
        return self.category    
    
    
    
    
class QQuestion(TimeStampModal):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.title
    
        
   
 
class Answer(TimeStampModal):
    title = models.CharField(max_length=250)
    question = models.ForeignKey(QQuestion, on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)
    
    
    
    def __str__(self):
        return self.title
    
class Progress(TimeStampModal):
    player = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="progress_user")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_started = models.BooleanField(default=False)
    is_completed = models.BooleanField(default=False)
        
    def __str__(self):
        return str(self.category)
    

    
    
    
    
class Result(TimeStampModal):
    score = models.CharField(max_length=200)
    player = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="result")
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    
    
    def __str__(self):
        return str(self.score)
                  
    
    

    


    

useraccount/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager


# Create your models here.
class User(AbstractUser):
    objects = UserManager()
    
    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
        


class profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    address = models.CharField(max_length=200,blank=True,null=True)
    avatar = models.ImageField(upload_to="profile",null=True,blank=True)
    
    def __str__(self):
        return self.user        

    
    
    

useraccount/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class CustomerRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields= ("username","password1","password2")

quizapp/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpRequest
from quizapp.models import QQuestion,Answer, Category, Progress, Result
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
# Create your views here.
def home(request):
    questions = QQuestion.objects.all()
    categories = Category.objects.all()
    answers = Answer.objects.all()
    context = {"questions":questions,"answers":answers,"categories":categories}
    return render(request,"home.html",context)

@login_required(login_url="user:login")
def result(request):
    answer_users = request.POST.getlist('answer_user') 
    print(answer_users)
    answers = Answer.objects.all()
    questions = QQuestion.objects.all()
    right_answer = []
    for answer in answers:
        if answer.is_correct == True:
            right_answer.append(answer.title)
        
        
    print(right_answer)
    
    marks_count = 0
    for answer_user in answer_users:
        for answer in right_answer:
            if answer == answer_user:
                marks_count = marks_count + 1
                             
    category_result = request.POST.get('result_category')
    # print(question2)
    # question1 = QQuestion.objects.get(title=question2)
    # print(question1)
    # category = Category.objects.filter()
    result = Result(score=marks_count,player=request.user,category=Category.objects.get(category=category_result))
    result.save()
    
    context = {"marks":marks_count}  
    
            
    return render(request,"result.html",context)


@login_required(login_url="user:login")
def q_question(request,categoryid):

    categories = Category.objects.get(id=categoryid)
    questions = QQuestion.objects.filter(category=categories)
    answers = Answer.objects.all()
    print(categories)
   

    obj,created = Progress.objects.get_or_create(
        is_started = True,
        is_completed = False,
        player = request.user,
        category=categories,
        defaults={
            "category":categories,
            "is_started":True,
            "is_completed":False,
  
        }
                        
        )
    
    context = {"questions":questions,"answers":answers,"categories":categories}
    
    return render(request,"question.html",context)


@login_required(login_url="user:login")
def progress(request):
    progresses = Progress.objects.filter(is_started=True,is_completed=False, player=request.user)
    print(progresses)

    context = {"progresses":progresses}
    return render(request,"progress.html",context)
    
    
@login_required(login_url="user:login")    
def completed(request):
    results = Result.objects.filter(player=request.user)

    context={"results":results}
    return render(request,"completed.html",context)

        
    

    
        


    

useraccount/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
from django.views.generic import CreateView
from useraccount.forms import CustomerRegisterForm
from django.urls import reverse_lazy
# Create your views here.

User = get_user_model()
class CustomLoginView(LoginView):
    template_name = 'login.html'

class CustomRegisterView(CreateView):
    model = User
    form_class = CustomerRegisterForm
    template_name="register.html"
    success_url = reverse_lazy("user:login")

quizapp/templates/completed.html
{% extends 'base_temp.html' %}

{% block maincontent %}
 <table class="table">
    <thead>
        <tr>
            <th>Sno</th>
            <th>Category</th>
            <th>Score</th>

        </tr>
        


    </thead>
    <tbody>
        {% for result in results %}

        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{result.category}}</td>
            <td>{{ result.score }}</td>
        </tr>
        {% endfor %}



    </tbody>




 </table>



{% endblock maincontent %}

quizapp/templates/home.html
{% extends 'base_temp.html' %}
{% block maincontent %}

{% load static %}
 
    <div class="mt-3 d-flex justify-content-center align-items-center">
        <div class="card shadow-lg p-3 mb-5 bg-white rounded" style="width: 24rem;">
            <img src="{% static 'images/QuizImage.svg' %}"  style="width: 22rem;height: 20rem;" class="card-img-top img-fluid" alt="Quiz Image">
            <div class="card-body">
                <h2 class="card-title"> Choose Category</h2>

                <h5 class="mt-4 py-2" >
                    <ul class="list-group">
                        {% for cat in categories %}
                        <li class="mt-2 list-group-item list-group-item-action" ><a class="text-decoration-none text-secondary text-capitalize" href="{% url 'quizapp:q_question' cat.id %}">{{cat.category}}</a></li>
            
                    {% endfor %}
                    </ul>
                </h5>
            </div>
          </div>
 
    </div>



{% endblock maincontent %}

quizapp/templates/progress.html
{% extends 'base_temp.html' %}
{% block maincontent %}
{% load static %}
<div class="mt-3 d-flex justify-content-center align-items-center">
    <div class="card shadow-lg p-3 mb-5 bg-white rounded" style="width: 24rem;" >
        <img src="{% static 'images/progressImage.svg' %}"  style="width: 22rem;height: 20rem;" class="card-img-top img-fluid" alt="Quiz Image">
        <div class="card-body">
            <h3 class="card-title"> Progress Quiz Category</h3>

            <h5 class="mt-4 py-2" >
                <ul class="list-group">
                    {% for progress in progresses %}
                  
                    <li class="mt-2 list-group-item list-group-item-action"><a class="text-decoration-none text-secondary text-capitalize" href="{% url 'quizapp:q_question' progress.category.id %}">{{ progress.category }}</a></li>
                    {% endfor %}

                </ul>
            </h5>
        </div>
      </div>

</div>
{% endblock maincontent %}

quizapp/templates/question.html
{% extends 'base_temp.html' %}

{% block maincontent %}
<h1>Questions</h1>
<form action="{% url 'quizapp:result' %}" method="post">{% csrf_token %}
    {% for question in questions %}

        <h3>{{forloop.counter|add:0}}. {{question.title}}</h3>
        {% for answer in question.answer_set.all %}
            
   
                <p><input type="checkbox" name="answer_user" id="answer_user" value="{{answer.title}}"> <span>{{answer.title}}</span></p>
               


        {% endfor %}
    {% endfor%}
    <input type="hidden" name="result_category" value="{{categories.category}}" >

    <button type="submit" class="btn btn-primary" >Check Result</button>
</form> 
{% endblock maincontent %}

quizapp/templates/result.html
{% extends 'base_temp.html' %}

{% block maincontent %}
<div class="mt-4">

<h2><b>Result: </b></h2>
<h4><b>Correct answer: </b>{{marks}}</h4>

</div>
{% endblock maincontent %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz App</title>
    {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/bs.min.css' %}">

    {% endblock stylesheet %}
</head>
<body>
        {% block content %}
    
        {% endblock content %}




    {% block script %}
    <script src="{% static 'js/bs.min.js' %}"></script>
    {% endblock script %}
</body>
</html>

templates/base_temp.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}

<div class="container">
{% block maincontent %}

{% endblock maincontent %}
</div>

{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <h2><a class="navbar-brand" href="/">Quiz App</a></h2>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'quizapp:progress' %}">Progress</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'quizapp:completed' %}">Completed</a>
          </li>
          {% if not request.user.is_active %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:login' %}">Login</a>
          </li>
          {% endif %}
          {% if request.user.is_active %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
          </li>
          {% endif %}
        </ul>
        {% comment %} <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> {% endcomment %}
      </div>
    </div>
  </nav>

useraccount/templates/login.html
{% extends 'base_temp.html' %}
{% block maincontent %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
<input type="submit" class="btn btn-primary" value="Log In">
</form>
<h2>Don't have an account ? </h2>
<a href="{% url 'user:register' %}">Register</a>
{% endblock maincontent %}

useraccount/templates/register.html
{% extends 'base_temp.html' %}
{% block maincontent %}


<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="signup">
</form>

<div class="m-3">
    <h3>Already have an account? </h3>
    <a class="btn btn-success" href="{% url 'user:login' %}">Login</a>
</div>
{% endblock maincontent %}